module.exports.adjectives = [
    'Glorious',
    'Ancient',
    'New',
    'Crazy',
    'Gloomy',
    'Terrible',
    'Perfect',
    'Good',
    'Great',
    'Excellent',
    'Best',
    'Fragrant',
    'Disregard',
    'Blue',
    'Wet',
    'Dry',
    'Tasty',
    'Golden'
]

module.exports.subjects = [
    'Video Games',
    'TV Shows',
    'Movies',
    'Workouts',
    'Recipies',
    'Computers',
    'Cell Phones',
    'Streaming Services',
    'Restaurants',
    'Offices',
    'Cars',
    'Songs',
    'Apples',
    'Drinks',
    'Pants',
    'Gloves',
    'Tacos',
    'Shirts',
    'Buildings',
    'Views',
    'Nuggets'
]